version: "3.8"

services:

  nginx:
    image: library/nginx:alpine
    container_name: dt_nginx
    restart: always
    depends_on:
      - web
    ports:
      - 80:80
    volumes:
      - static-volume:/static
      - ./nginx.conf:/etc/nginx/nginx.conf
      - media-volume:/media
  db:
    image: library/postgres:12.0-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    env_file:
      - .env

    ports:
      - 5432:5432
    volumes:
      - dt-pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: web
    restart: always
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 project.wsgi:application
    environment:
      - SECRET_KEY
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static-volume:/app/src/static
      - media-volume:/app/src/media

volumes:
  static-volume:
  media-volume:
  dt-pgdata:


networks:
  default:
    name: dt-network