# Generated by Django 4.0.4 on 2022-05-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название аллергена')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название в меню')),
                ('nutritional_value', models.PositiveSmallIntegerField(verbose_name='Пищевая ценность в Ккал')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='uploads/restaurant/images', verbose_name='Изображение блюда')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Салаты'), (2, 'Первое блюда'), (3, 'Холодные блюда'), (4, 'Горячие блюда'), (5, 'Десерты'), (6, 'Напитки')], verbose_name='Категория блюда')),
                ('allergens', models.ManyToManyField(related_name='allergens', to='restaurant.allergen', verbose_name='Пищевые аллергены')),
            ],
            options={
                'ordering': ('category',),
            },
        ),
    ]
